name: Tests

on:
  push:
    tags:
      - '!*'
    branches:
      - '*'
  pull_request:
    tags:
      - '!*'
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    name: 'Run tests: Node ${{ matrix.node }} on ${{ matrix.os }}'
    strategy:
      matrix:
        os: [
         ubuntu-latest,
        #  macos-latest,
        #  windows-latest
        ]
        node: [
          # 'lts/*', # latest node
          # 12.14.1, # vscode >= 1.49.0
          # 12.8.1,  # vscode >= 1.43.0 < 1.49.0
          12.4.0,  # vscode >= 1.40.0 < 1.43.0
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - run: |
          echo ${{ env.GITHUB_SHA}}
          echo ${{ env.GITHUB_BRANCH}}

      - name: "Setting up Node.js ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Installing Dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Uploading code coverage artifacts
        if: >
          (
          success() &&
          matrix.os == 'ubuntu-latest' &&
          matrix.node == '12.4.0' &&
          github.repository_owner == 'vscode-icons' &&
          github.actor != 'dependabot[bot]'
          )
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/
