name: Update Wiki Page Icons List

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update:
    name: Update Wiki Pages
    runs-on: ubuntu-latest
    if: github.repository == 'vscode-icons/vscode-icons'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.14.1
      - run: npm ci
      - name: Compile
        run: npm run compile
      - name: Update Wiki Page Icons List
        run: npx vscode-icons/wpilgenerator
        env:
          TRAVIS_SECURE_ENV_VARS: 'true'
          TRAVIS_PULL_REQUEST: 'false'
          TRAVIS_BRANCH: master
          TRAVIS_OS_NAME: linux
          TRAVIS_REPO_SLUG: vscode-icons/vscode-icons
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
